package com.capstone.jfc.enums;

public enum JobCategory {
    SCAN_PULL_CODESCAN,
    SCAN_PULL_DEPENDABOT,
    SCAN_PULL_SECRETSCAN,
    SCAN_PARSE_CODESCAN,
    SCAN_PARSE_DEPENDABOT,
    SCAN_PARSE_SECRETSCAN,
    UPDATE_FINDING,
    CREATE_TICKET,
    UPDATE_TICKET,
    RUNBOOK_JOB
}
