server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone_db
    username: capstone
    password: capstone
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: jfc-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# The topics if you want to override
topics:
  jfc_auth: jfc_auth
  jfc_tool: jfc_tool
  jfc_parser: jfc_parser
  job_ack: job-acknowledgement-topic
  bg_jobs: jfc_bgJobs
  job_ingestion_topic: job_ingestion_topic

logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
    kafka: ERROR
